(function(){"use strict";
var reduce=window.matchMedia("(prefers-reduced-motion: reduce)").matches;
var $=function(s,r){return(r||document).querySelector(s)},$$=function(s,r){return Array.prototype.slice.call((r||document).querySelectorAll(s))};
function track(name,detail){window.dataLayer=window.dataLayer||[];window.dataLayer.push({event:name,forge:detail||{}});document.dispatchEvent(new CustomEvent("forge:"+name,{detail:detail||{}}))}
function prepareMetadata(){var preview=location.hostname.endsWith(".vercel.app")||location.hostname==="127.0.0.1"||location.hostname==="localhost";if(preview){var robots=document.createElement("meta");robots.name="robots";robots.content="noindex,nofollow";document.head.appendChild(robots)}var origin=$('meta[name="forge:production-origin"]');if(origin&&origin.content){$$('[data-production-path]').forEach(function(el){var path=el.dataset.productionPath,value=new URL(path,origin.content).href;if(el.tagName==="LINK")el.href=value;else el.content=value})}}
prepareMetadata();
$$('[data-event]').forEach(function(el){el.addEventListener("click",function(){track(el.dataset.event,{label:el.textContent.trim()})})});
var header=$('[data-header]');window.addEventListener("scroll",function(){header.classList.toggle("scrolled",window.scrollY>24)},{passive:true});
var menu=$('[data-menu]'),mobileNav=$('[data-mobile-nav]');menu.addEventListener("click",function(){var open=menu.getAttribute("aria-expanded")==="true";menu.setAttribute("aria-expanded",String(!open));mobileNav.hidden=open});$$('a',mobileNav).forEach(function(a){a.addEventListener("click",function(){mobileNav.hidden=true;menu.setAttribute("aria-expanded","false")})});

var workdayImage=$('[data-workday-image]'),workdayCaption=$('[data-workday-caption]'),workdaySteps=$$('[data-workday-step]');function showWorkday(step){workdaySteps.forEach(function(x){x.classList.toggle("active",x===step)});workdayImage.src=step.dataset.src;workdayImage.alt=step.dataset.alt;workdayCaption.innerHTML="<time>"+$('time',step).textContent+"</time><strong>"+$('strong',step).textContent+"</strong>"}if(!reduce&&"IntersectionObserver"in window){var workdayObserver=new IntersectionObserver(function(entries){entries.forEach(function(entry){if(entry.isIntersecting)showWorkday(entry.target)})},{rootMargin:"-35% 0px -45%",threshold:0});workdaySteps.forEach(function(step){workdayObserver.observe(step)})}

var docket=$('[data-job-docket]'),status=$('[data-job-status]');if("IntersectionObserver"in window){new IntersectionObserver(function(entries){entries.forEach(function(entry){if(entry.isIntersecting)docket.hidden=false})},{threshold:.1}).observe($('[data-job-zone]'));$$('[data-job-stage]').forEach(function(stage){new IntersectionObserver(function(entries){entries.forEach(function(entry){if(entry.isIntersecting)status.textContent=stage.dataset.jobStage})},{threshold:.35}).observe(stage)})}
var survey=$('[data-survey-demo]');$('[data-structure-findings]').addEventListener("click",function(){survey.classList.toggle("show-findings");status.textContent="5 FINDINGS REVIEWED"});
$$('[data-review-action]').forEach(function(button){button.addEventListener("click",function(){$$('[data-review-action]').forEach(function(x){x.classList.toggle("active",x===button)});var messages={approve:"Approved findings now carry into the report and quote.",edit:"Finding opened for human correction before it moves.",remove:"Finding removed. The source capture stays attached to the job."};$('[data-review-output]').textContent=messages[button.dataset.reviewAction];if(button.dataset.reviewAction==="approve")status.textContent="REPORT READY"})});
var attention=$('[data-attention]');$('[data-attention-trigger]').addEventListener("click",function(){attention.classList.add("collapsed");$('[data-needs]').hidden=false;this.hidden=true});

var ai={quotes:'<div class="ai-state-path"><span>QUESTION</span><i>↓</i><span>REAL RECORDS</span></div><table class="result-table"><thead><tr><th>QUOTE</th><th>CUSTOMER</th><th>VALUE</th><th>STATE</th></tr></thead><tbody><tr><td>Q-02841</td><td>J. Smith</td><td>£8,200</td><td>NOT FOLLOWED UP</td></tr><tr><td>Q-02798</td><td>Demo customer</td><td>£6,450</td><td>NOT FOLLOWED UP</td></tr></tbody></table>',drafts:'<div class="ai-state-path"><span>ACTION</span><i>↓</i><span>DRAFT READY</span></div><table class="result-table"><thead><tr><th>QUOTE</th><th>CUSTOMER</th><th>VALUE</th><th>NEW STATE</th></tr></thead><tbody><tr><td>Q-02841</td><td>J. Smith</td><td>£8,200</td><td>DRAFT READY</td></tr><tr><td>Q-02798</td><td>Demo customer</td><td>£6,450</td><td>DRAFT READY</td></tr></tbody></table><p>Nothing has been sent.</p>',invoices:'<div class="ai-state-path"><span>QUESTION</span><i>↓</i><span>COMPLETED JOBS</span></div><table class="result-table"><thead><tr><th>JOB</th><th>CUSTOMER</th><th>VALUE</th><th>STATE</th></tr></thead><tbody><tr><td>JOB 02841</td><td>J. Smith</td><td>£4,840</td><td>COMPLETE</td></tr><tr><td>JOB 02817</td><td>Demo customer</td><td>£2,160</td><td>COMPLETE</td></tr></tbody></table>',prepare:'<div class="ai-state-path"><span>ACTION</span><i>↓</i><span>INVOICE DRAFT READY</span></div><table class="result-table"><thead><tr><th>JOB</th><th>CUSTOMER</th><th>VALUE</th><th>NEW STATE</th></tr></thead><tbody><tr><td>JOB 02841</td><td>J. Smith</td><td>£4,840</td><td>INVOICE DRAFT READY</td></tr><tr><td>JOB 02817</td><td>Demo customer</td><td>£2,160</td><td>INVOICE DRAFT READY</td></tr></tbody></table><p>Prepared for review. Nothing has been sent.</p>'};
function showAI(key){$$('[data-command]').forEach(function(button){button.classList.toggle("active",button.dataset.command===key)});$('[data-ai-result]').innerHTML=ai[key]}$$('[data-command]').forEach(function(button){button.addEventListener("click",function(){showAI(button.dataset.command)})});showAI("quotes");

var flows={roofing:["ENQUIRY","SURVEY","REPORT","QUOTE","CREW","COMPLETION","WARRANTY"],electrical:["CALL","SITE CHECK","TEST","REMEDIALS","CERTIFICATE","INVOICE"],maintenance:["REQUEST","TRIAGE","SLA","ENGINEER","EVIDENCE","SIGN-OFF","INVOICE"]};
var tradeImages={roofing:{desktop:"public/cinematic-v2/trade-roofing.webp",mobile:"public/cinematic-v3/trade-roofing-mobile.webp",alt:"Forge adapting around a real roofing workflow"},electrical:{desktop:"public/cinematic-v2/trade-electrical.webp",mobile:"public/cinematic-v3/trade-electrical-mobile.webp",alt:"Forge adapting around a real electrical workflow"},maintenance:{desktop:"public/cinematic-v2/trade-commercial-maintenance.webp",mobile:"public/cinematic-v3/trade-commercial-maintenance-mobile.webp",alt:"Forge adapting around a real commercial maintenance workflow"}};
function renderTrade(key){var next=tradeImages[key];$('[data-trade-image]').src=next.desktop;$('[data-trade-image]').alt=next.alt;$('[data-trade-source]').srcset=next.mobile;$('[data-trade-flow]').innerHTML=flows[key].map(function(item){return"<span>"+item+"</span>"}).join("")}$$('[data-trade]').forEach(function(button){button.addEventListener("click",function(){$$('[data-trade]').forEach(function(x){x.setAttribute("aria-selected",String(x===button))});renderTrade(button.dataset.trade);track("trade_workflow_change",{trade:button.dataset.trade})})});renderTrade("roofing");

var productViews={today:{desktop:"public/product/desktop/today-dashboard.svg",mobile:"public/product/mobile/today.svg",alt:"Forge Today operating view",caption:"TODAY · THE WORK THAT MATTERS NOW"},money:{desktop:"public/product/desktop/money-dashboard.svg",mobile:"public/product/mobile/completion-to-invoice.svg",alt:"Forge money and completion view",caption:"MONEY · WORK COMPLETED, INVOICES PREPARED"},job:{desktop:"public/product/desktop/job-02841.svg",mobile:"public/product/mobile/survey-findings.svg",alt:"Forge Job 02841 context",caption:"JOB 02841 · THE CONTEXT COMES WITH IT"},field:{desktop:"public/product/desktop/job-02841.svg",mobile:"public/product/mobile/survey-recording.svg",alt:"Forge field survey view",caption:"FIELD · CAPTURE IT ONCE"},ai:{desktop:"public/product/desktop/ai-office.svg",mobile:"public/product/mobile/ask-forge.svg",alt:"Forge AI Office view",caption:"AI OFFICE · ASK, PREPARE, REVIEW"}};
var currentProduct="today";function showProduct(key){currentProduct=key;var view=productViews[key],mobile=window.matchMedia("(max-width:700px)").matches,image=$('[data-product-image]');image.src=mobile?view.mobile:view.desktop;image.alt=view.alt;$('[data-product-caption]').textContent=view.caption;$$('[data-product]').forEach(function(button){button.setAttribute("aria-selected",String(button.dataset.product===key))})}$$('[data-product]').forEach(function(button){button.addEventListener("click",function(){showProduct(button.dataset.product)})});window.addEventListener("resize",function(){showProduct(currentProduct)},{passive:true});showProduct("today");
$$('[data-document-src]').forEach(function(button){button.addEventListener("click",function(){$$('[data-document-src]').forEach(function(x){x.classList.toggle("selected",x===button)});var image=$('[data-document-image]');image.src=button.dataset.documentSrc;image.alt=button.dataset.documentName;$('[data-document-caption]').textContent=button.dataset.documentName})});

var bp=$('[data-blueprint]'),form=$('[data-blueprint-form]'),state={step:1,trade:"",team:"",tools:[],pain:""},next=$('[data-next]',bp),back=$('[data-back]',bp);
function valid(){return state.step===1?!!state.trade:state.step===2?!!state.team:state.step===3?state.tools.length>0:!!state.pain}
function sync(){$$('[data-step]',form).forEach(function(x){x.hidden=Number(x.dataset.step)!==state.step});$('[data-progress-fill]').style.width=state.step*25+"%";$('[data-progress-text]').textContent="QUESTION "+state.step+" OF 4";back.hidden=state.step===1;next.disabled=!valid();next.textContent=state.step===4?"Build my Blueprint":"Continue"}
$$('[data-single] button',form).forEach(function(button){button.addEventListener("click",function(){var group=button.parentElement.dataset.single;state[group]=button.dataset.value;$$('button',button.parentElement).forEach(function(x){x.classList.toggle("selected",x===button)});sync()})});
$$('[data-multi] input',form).forEach(function(input){input.addEventListener("change",function(){state.tools=$$('[data-multi] input:checked',form).map(function(x){return x.value});sync()})});
var stepEvents=["blueprint_step_1","blueprint_step_2","blueprint_step_3","blueprint_step_4"];
next.addEventListener("click",function(){if(!valid())return;track(stepEvents[state.step-1],{answer:state.step===1?state.trade:state.step===2?state.team:state.step===3?state.tools:state.pain});if(state.step<4){state.step++;sync();bp.scrollIntoView({behavior:reduce?"auto":"smooth",block:"start"})}else build()});back.addEventListener("click",function(){if(state.step>1){state.step--;sync()}});
function build(){form.querySelectorAll('.blueprint-step,.blueprint-nav').forEach(function(x){x.hidden=true});$('.blueprint-progress',bp).hidden=true;$('[data-blueprint-result]').hidden=false;var modules={Enquiries:"Enquiries · Customers · Routing",Quotes:"Surveys · Quotes · Follow-ups",Surveys:"Mobile survey · Findings · Reports",Paperwork:"Documents · Approvals · Records","Jobs & team":"Jobs · Diary · Team context","Customer updates":"Messages · Drafts · Follow-ups",Invoicing:"Completion · Invoices · Xero","Finding information":"Job context · Search · Timeline","Follow-ups":"Attention · Drafts · Tracking","Everything comes through me":"Attention · Approvals · Team context"};var priorities=["Create one route from "+state.pain.toLowerCase()+" into the job.","Carry context across the "+state.team+" people who need it.","Set approval points so Forge prepares work without taking control away."];state.priorities=priorities;state.modules=modules[state.pain];$('[data-result-title]').textContent=state.trade+" workflow · "+state.team+" people";$('[data-result-summary]').textContent="Start where "+state.pain.toLowerCase()+" creates the most owner dependency, while keeping the tools the team already knows.";$('[data-result-priorities]').innerHTML=priorities.map(function(item){return"<li>"+item+"</li>"}).join("");$('[data-result-modules]').textContent=state.modules;$('[data-result-tools]').textContent=state.tools.join(" · ");$('[data-result-trade]').textContent=state.trade;$('[data-result-team]').textContent=state.team;$('[data-result-tools-mobile]').textContent=state.tools.join(" · ");$('[data-result-pain]').textContent=state.pain;track("blueprint_generated",state)}
form.addEventListener("focusin",function(event){if(event.target.matches("input[name]"))track("contact_form_start",{})},{once:true});
form.addEventListener("submit",async function(event){event.preventDefault();var required=$$('[required]',form),invalid=required.some(function(input){return!input.checkValidity()});if(invalid){required.find(function(input){return!input.checkValidity()}).reportValidity();return}var submit=$('[data-submit-blueprint]'),note=$('[data-form-status]');submit.disabled=true;submit.textContent="Sending Blueprint…";note.className="form-note";note.textContent="Sending your Blueprint securely…";var contact={name:$('[name="name"]',form).value.trim(),company:$('[name="company"]',form).value.trim(),email:$('[name="email"]',form).value.trim(),phone:$('[name="phone"]',form).value.trim(),website:$('[name="website"]',form).value};try{var response=await fetch('/api/blueprint',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.assign({},contact,{trade:state.trade,teamSize:state.team,tools:state.tools,pain:state.pain,modules:state.modules,priorities:state.priorities}))}),payload=await response.json().catch(function(){return{}});if(!response.ok){var failure=new Error(payload.error||'submit_failed');failure.code=payload.error;throw failure}note.className="form-note success";note.textContent="Blueprint sent successfully. Thanks — we’ll use it when we talk.";submit.textContent="Blueprint sent ✓";track("contact_form_submit",state)}catch(error){note.className="form-note error";note.textContent=error.code==="enquiry_destination_not_configured"?"Blueprint delivery is not configured yet. Your answers remain here and have not been sent.":"We couldn’t send that just now. Your answers remain here — please try again in a moment.";submit.disabled=false;submit.textContent="Try sending my Blueprint again";track("contact_form_error",{reason:error.message})}});
if("IntersectionObserver"in window){var start=new IntersectionObserver(function(entries,observer){entries.forEach(function(entry){if(entry.isIntersecting){track("blueprint_start",{});observer.disconnect()}})},{threshold:.35});start.observe(bp)}sync();
})();
